const eventsData = [
    // ============ UPCOMING EVENTS (2026 - 2027) ============
    {
        id: 101,
        name: "🌿 Spring Food Festival 2026",
        description: "Celebrate spring with 30+ food stalls, live music, and cooking demonstrations from top chefs.",
        price: 800,
        discountedPrice: 599,
        date: "2026-06-15",
        time: "11:00 AM",
        venue: "Central Park, Connaught Place",
        availableSeats: 250,
        totalSeats: 500,
        image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=500",
        type: "Festival",
        includes: ["Entry Ticket", "Food Voucher (₹200)", "Live Music", "Kids Zone", "Free Parking"],
        duration: "8 hours",
        chef: "Multiple Celebrity Chefs",
        rating: 4.9,
        reviews: 234
    },
    {
        id: 102,
        name: "🍕 Master Pizza Workshop",
        description: "Learn authentic Neapolitan pizza making from world-champion pizzaiolo.",
        price: 2500,
        discountedPrice: 1999,
        date: "2026-06-20",
        time: "2:00 PM",
        venue: "Pizza Academy - Saket",
        availableSeats: 15,
        totalSeats: 25,
        image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=500",
        type: "Workshop",
        includes: ["All Ingredients", "Professional Apron", "Certificate", "Take-home Pizza"],
        duration: "3 hours",
        chef: "Chef Giovanni",
        rating: 4.9,
        reviews: 89
    },
    {
        id: 103,
        name: "🍣 Omakase Experience",
        description: "Exclusive 15-course omakase dinner by Master Sushi Chef. Limited to only 10 guests!",
        price: 6500,
        discountedPrice: 4999,
        date: "2026-06-25",
        time: "8:00 PM",
        venue: "Sushi Master - Hauz Khas",
        availableSeats: 8,
        totalSeats: 10,
        image: "https://images.unsplash.com/photo-1617196034796-73dfa7b1fd2f?w=500",
        type: "Fine Dining",
        includes: ["15-Course Omakase", "Sake Pairing", "Chef's Table", "Welcome Champagne"],
        duration: "2.5 hours",
        chef: "Chef Kenji",
        rating: 5.0,
        reviews: 45
    },
    {
        id: 104,
        name: "🌶️ Indian Street Food Tour",
        description: "Guided food tour through Delhi's best street food spots. Taste 15+ signature dishes!",
        price: 1500,
        discountedPrice: 1199,
        date: "2026-07-05",
        time: "5:00 PM",
        venue: "Chandni Chowk, Old Delhi",
        availableSeats: 20,
        totalSeats: 30,
        image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=500",
        type: "Tour",
        includes: ["Food Tastings (15+ items)", "Local Guide", "Food Map", "Tote Bag"],
        duration: "4 hours",
        chef: "Local Food Experts",
        rating: 4.8,
        reviews: 167
    },
    {
        id: 105,
        name: "🍰 Luxury Afternoon Tea",
        description: "Indulge in luxurious afternoon tea with fine pastries, scones, and premium teas.",
        price: 1800,
        discountedPrice: 1499,
        date: "2026-07-10",
        time: "3:00 PM",
        venue: "The Grand Hotel - Connaught Place",
        availableSeats: 25,
        totalSeats: 40,
        image: "https://images.unsplash.com/photo-1551024506-0bccd828d307?w=500",
        type: "Luxury",
        includes: ["Selection of Teas", "Pastry Platter", "Scones with Cream", "Live Piano"],
        duration: "2 hours",
        chef: "Pastry Chef Emma",
        rating: 4.9,
        reviews: 78
    },
    {
        id: 106,
        name: "🔥 Summer BBQ Party",
        description: "Epic summer BBQ party with unlimited grilled meats, seafood, and live DJ!",
        price: 2000,
        discountedPrice: 1699,
        date: "2026-07-18",
        time: "7:00 PM",
        venue: "Rooftop Garden - Saket",
        availableSeats: 50,
        totalSeats: 100,
        image: "https://images.unsplash.com/photo-1529694157879-4e0c0f3b7e6b?w=500",
        type: "Party",
        includes: ["Unlimited BBQ", "Welcome Drink", "Live DJ", "Photo Booth"],
        duration: "4 hours",
        chef: "Chef Ranveer",
        rating: 4.7,
        reviews: 203
    },
    {
        id: 107,
        name: "🥟 Dimsum Making Class",
        description: "Learn to make 5 types of dimsum including har gow, siu mai, and soup dumplings.",
        price: 2200,
        discountedPrice: 1899,
        date: "2026-07-25",
        time: "11:00 AM",
        venue: "Dragon Wok - Indiranagar",
        availableSeats: 12,
        totalSeats: 20,
        image: "https://images.unsplash.com/photo-1563241527-3004b7be0f6a?w=500",
        type: "Workshop",
        includes: ["All Ingredients", "Bamboo Steamer", "Recipe Cards", "Lunch Included"],
        duration: "3 hours",
        chef: "Chef Mei Lin",
        rating: 4.9,
        reviews: 56
    },
    {
        id: 108,
        name: "🍷 Wine & Cheese Pairing Evening",
        description: "Sophisticated evening of premium wine and artisanal cheese pairing.",
        price: 3000,
        discountedPrice: 2499,
        date: "2026-08-01",
        time: "7:30 PM",
        venue: "The Wine Bar - MG Road",
        availableSeats: 30,
        totalSeats: 50,
        image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=500",
        type: "Tasting",
        includes: ["6 Wine Tastings", "Artisanal Cheese Board", "Sommelier Guide", "Wine Glass Gift"],
        duration: "2.5 hours",
        chef: "Sommelier Rajesh",
        rating: 4.8,
        reviews: 112
    },
    {
        id: 109,
        name: "🎂 Cake Decorating Masterclass",
        description: "Learn professional cake decorating techniques including buttercream flowers.",
        price: 2800,
        discountedPrice: 2299,
        date: "2026-08-10",
        time: "10:00 AM",
        venue: "Baking Studio - Koramangala",
        availableSeats: 10,
        totalSeats: 15,
        image: "https://images.unsplash.com/photo-1551024506-0bccd828d307?w=500",
        type: "Workshop",
        includes: ["All Materials", "Cake to Take Home", "Decorating Tools", "Certificate"],
        duration: "4 hours",
        chef: "Chef Priya",
        rating: 4.9,
        reviews: 89
    },
    {
        id: 110,
        name: "🌙 Moonlight Dinner Cruise",
        description: "Romantic dinner cruise with 5-course meal, live music, and stargazing.",
        price: 4500,
        discountedPrice: 3999,
        date: "2026-08-15",
        time: "7:00 PM",
        venue: "Dinner Cruise - Boat Club",
        availableSeats: 40,
        totalSeats: 60,
        image: "https://images.unsplash.com/photo-1467810563316-54755b6f186c?w=500",
        type: "Romantic",
        includes: ["5-Course Dinner", "Welcome Champagne", "Live Music", "Cruise Ride"],
        duration: "3 hours",
        chef: "Chef Special",
        rating: 4.9,
        reviews: 234
    },

    // ============ PAST EVENTS (2024-2025) ============
    {
        id: 1,
        name: "🎪 New Year's Eve Gala 2024",
        description: "Spectacular New Year celebration with 5-course dinner, live band, and midnight champagne toast.",
        price: 5000,
        discountedPrice: 3999,
        date: "2024-12-31",
        time: "8:00 PM",
        venue: "Grand Hotel - Connaught Place",
        availableSeats: 0,
        totalSeats: 150,
        image: "https://images.unsplash.com/photo-1467810563316-54755b6f186c?w=500",
        type: "Gala",
        includes: ["5-Course Dinner", "Live Band", "Midnight Champagne", "DJ Night"],
        duration: "5 hours",
        chef: "Chef Vikas",
        rating: 4.8,
        reviews: 312
    },
    {
        id: 2,
        name: "🍷 Winter Wine Festival",
        description: "Premium wine tasting event with 30+ international wines and gourmet food pairing.",
        price: 3500,
        discountedPrice: 2999,
        date: "2025-01-15",
        time: "6:00 PM",
        venue: "Wine Cellar - Saket",
        availableSeats: 0,
        totalSeats: 80,
        image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=500",
        type: "Festival",
        includes: ["Wine Tasting", "Gourmet Food", "Live Jazz", "Souvenir Glass"],
        duration: "4 hours",
        chef: "Sommeliers",
        rating: 4.7,
        reviews: 189
    },
    {
        id: 3,
        name: "🌸 Spring Brunch Fest",
        description: "Luxurious spring brunch with unlimited mimosas, garden seating, and live acoustic music.",
        price: 1800,
        discountedPrice: 1499,
        date: "2025-03-20",
        time: "11:00 AM",
        venue: "Garden Cafe - MG Road",
        availableSeats: 0,
        totalSeats: 100,
        image: "https://images.unsplash.com/photo-1533777857889-4be7c70b33f7?w=500",
        type: "Brunch",
        includes: ["Unlimited Buffet", "Free-flowing Mimosas", "Live Music", "Garden Seating"],
        duration: "4 hours",
        chef: "Chef Maria",
        rating: 4.8,
        reviews: 156
    },
    {
        id: 4,
        name: "🍕 Pizza Festival 2025",
        description: "Celebrate everything pizza with 20+ pizza vendors, live competitions, and unlimited slices!",
        price: 1200,
        discountedPrice: 999,
        date: "2025-05-10",
        time: "12:00 PM",
        venue: "Pizza Paradise - Saket",
        availableSeats: 0,
        totalSeats: 200,
        image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=500",
        type: "Festival",
        includes: ["Unlimited Pizza", "Drinks", "Live Competition", "Goodie Bag"],
        duration: "6 hours",
        chef: "Pizza Chefs",
        rating: 4.9,
        reviews: 278
    },
    {
        id: 5,
        name: "🍣 Sushi Fest 2025",
        description: "Annual sushi festival featuring 50+ sushi varieties from top Japanese restaurants.",
        price: 2000,
        discountedPrice: 1699,
        date: "2025-06-30",
        time: "7:00 PM",
        venue: "Sushi Master - Hauz Khas",
        availableSeats: 0,
        totalSeats: 120,
        image: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=500",
        type: "Festival",
        includes: ["Sushi Tasting", "Sake Included", "Cooking Demo", "Chopstick Gift"],
        duration: "3 hours",
        chef: "Chef Hiroshi",
        rating: 4.8,
        reviews: 145
    }
];

// Helper function to get upcoming events
function getUpcomingEvents() {
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    return eventsData.filter(event => new Date(event.date) >= today);
}

// Helper function to get past events
function getPastEvents() {
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    return eventsData.filter(event => new Date(event.date) < today);
}